server:
  port: 9000

logging:
  level:
    org.springframework.security: trace
    org.springframework.security.oauth2: trace
    org.hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
        ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
    generate-ddl: true



  datasource:
    url: jdbc:mysql://localhost:3306/auth_db?createDatabaseIfNotExist=false&userSSL=false&serverTimezone=UTC
    username: root
    password: S3cret4sa
    driverClassName: com.mysql.cj.jdbc.Driver
#  security:
#    oauth2:
#      authorizationserver:
#        client:
#          oidc-client:
#            registration:
#              client-id: "oidc-client"
#              client-secret: "{noop}secret"
#              client-authentication-methods:
#                - "client_secret_basic"
#              authorization-grant-types:
#                - "authorization_code"
#                - "refresh_token"
#              redirect-uris:
#                - "http://127.0.0.1:8080/login/oauth2/code/oidc-client"
#              post-logout-redirect-uris:
#                - "http://127.0.0.1:8080/"
#              scopes:
#                - "openid"
#                - "profile"
#            require-authorization-consent: true